bluerobotics/mavlink-server

- .github/workflows/build.yml
> ci: Add first version

- .github/workflows/build.yml
- Cargo.lock
- Cargo.toml
- src/cli.rs
- src/drivers/file/server.rs
- src/drivers/mod.rs
- src/drivers/tcp/client.rs
- src/drivers/tcp/server.rs
- src/drivers/udp/client.rs
- src/drivers/udp/server.rs
- src/logger.rs
- src/main.rs
It validates legacy formats as well url formats.
Also allows custom legacy formats to be compatible with previous tools.
> Add better endpoint for string configuration

- src/drivers/fake.rs
- src/drivers/file/server.rs
- src/drivers/tcp/client.rs
- src/drivers/tcp/server.rs
- src/drivers/udp/client.rs
- src/drivers/udp/server.rs
all merged by groups:
* std
* libs
* crate
> src: drivers: Reorganize imports

- src/drivers/fake.rs
- src/drivers/file/client.rs
- src/drivers/file/server.rs
- src/drivers/mod.rs
- src/drivers/serial/mod.rs
- src/drivers/tcp/client.rs
- src/drivers/tcp/server.rs
- src/drivers/udp/client.rs
- src/drivers/udp/server.rs
- src/hub.rs
> drivers: Merge DriverInfo and DriverExt

- src/drivers/fake.rs
> drivers: fake: sink: Add human friendly message

- Cargo.lock
- Cargo.toml
- src/drivers/mod.rs
- src/main.rs
- src/web/endpoints.rs
- src/web/html/index.html
- src/web/html/vue.global.js
- src/web/mod.rs
Add initial web server to be used around the application
> Web: Add first commit

- src/drivers/fake.rs
- src/drivers/mod.rs
- src/drivers/serial/mod.rs
- src/drivers/tcp/client.rs
- src/drivers/tcp/mod.rs
- src/drivers/tcp/server.rs
- src/drivers/tlog/reader.rs
- src/drivers/tlog/writer.rs
- src/drivers/udp/client.rs
- src/drivers/udp/server.rs
- src/hub/actor.rs
- src/hub/mod.rs
- src/hub/protocol.rs
- src/stats/accumulated/driver.rs
- src/stats/accumulated/messages.rs
- src/stats/accumulated/mod.rs
- src/stats/actor.rs
- src/stats/driver.rs
- src/stats/messages.rs
- src/stats/mod.rs
- src/stats/protocol.rs
> Add message stats

- Cargo.lock
- Cargo.toml
- src/hub/mod.rs
- src/main.rs
- src/protocol.rs
- src/stats/accumulated/driver.rs
- src/stats/accumulated/messages.rs
- src/stats/accumulated/mod.rs
- src/stats/actor.rs
- src/stats/mod.rs
- src/web/endpoints.rs
- src/web/mod.rs
/stats/driver
```json
{"ef09b924-950b-5357-b6c0-bd312e43867c":{"name":"UdpClient","driver_type":"UdpClient","stats":{"input":{"last_message":{"origin":"192.168.0.130:14550","timestamp":1727888067905773},"last_update_us":1727888067905776,"messages":2645,"bytes":81571,"delay":14162},"output":{"last_message":{"origin":"","timestamp":1727888067191179},"last_update_us":1727888067191301,"messages":9,"bytes":189,"delay":1985}}},"e09d04cd-3212-5d7e-81e0-3b481bd21af9":{"name":"Default","driver_type":"Rest","stats":{"input":null,"output":{"last_message":{"origin":"192.168.0.130:14550","timestamp":1727888067905773},"last_update_us":1727888067906101,"messages":2655,"bytes":81781,"delay":1125090}}}}
```
/stats/hub
```json
{"last_message":{"origin":"192.168.0.130:14550","timestamp":1727888109245290},"la …
```
> Add stats  endpoint

- src/web/mod.rs
- src/webpage/Cargo.toml
- src/webpage/src/app.rs
- src/webpage/src/main.rs
> Add stats information in webpage

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/web/mod.rs
The ctrl_c was intended to be used until we have the web server running.
> Remove ctrl_c

- src/lib/cli.rs
- src/lib/web/mod.rs
> cli: small fixes

- src/lib/drivers/udp/mod.rs
Addressing https://github.com/bluerobotics/BlueOS/pull/2974#pullrequestreview-2392151277
> src: lib: drivers: udp: Fix verbosity of UDP send errors

- src/lib/drivers/fake.rs
> lib: driver: fake: Fix fake source running as sink

- Cargo.lock
- Cargo.toml
- src/lib/web/endpoints.rs
- src/lib/web/mod.rs
This allows full information of all dependencies and package via the web api
> Cargo: Add toml package

- src/webpage/src/app.rs
Allow frontend to reconnect with back if restarted
> webpage: app: Add reconnect

- src/lib/drivers/rest/mod.rs
- src/lib/drivers/serial/mod.rs
- src/lib/drivers/tcp/client.rs
- src/lib/drivers/tcp/server.rs
- src/lib/drivers/udp/client.rs
- src/lib/drivers/udp/server.rs
> src: lib: Fix broken loop delay logic all over

- src/webpage/src/app.rs
> webpage: Improve split and dock organization

- src/lib/cli.rs
- src/lib/web/mod.rs
- src/main.rs
> Add `--web-server` CLI arg

- src/lib/cli.rs
- src/lib/hub/mod.rs
> Add `--mavlink-system-id`, `--mavlink-component-id` and `mavlink-heartbeat-frequency` CLI args

- src/lib/cli.rs
- src/lib/drivers/rest/mod.rs
- src/lib/drivers/zenoh/mod.rs
- src/lib/hub/actor.rs
- src/lib/protocol.rs
- src/lib/web/mod.rs
> Add `--mavlink-version` CLI arg + Rest refactor

- .github/workflows/build.yml
- src/lib/drivers/mod.rs
- src/lib/drivers/udp/client.rs
- tests/udp.rs
> drivers: udp: Add more direction control

- src/webpage/src/app.rs
> webpage: app: Show vehicle information

- .github/workflows/build.yml
> CI: Use comma separated list for rustup targets

- .gitmodules
- Cargo.lock
- Cargo.toml
- src/lib/drivers/rest/autopilot/ardupilot.rs
- src/lib/drivers/rest/autopilot/mod.rs
- src/lib/drivers/rest/autopilot/parameters/mod.rs
- src/lib/drivers/rest/control.rs
- src/lib/web/routes/v1/rest/mod.rs
- src/lib/web/routes/v1/rest/vehicles.rs
> Parameters handle 

- src/lib/drivers/rest/control.rs
- src/lib/web/routes/v1/rest/mod.rs
- src/lib/web/routes/v1/rest/vehicles.rs
> Move parameter handle to endpoint and websocket

- src/lib/drivers/rest/control.rs
solves #134 
Quite an esoteric panic there.
> src: lib: drivers: rest: Workaround anyhow internal panic

- src/webpage/src/app.rs
- src/webpage/src/lib.rs
- src/webpage/src/tabs/control.rs
- src/webpage/src/tabs/mod.rs
> app: Add interface to change parameter

- .github/workflows/build.yml
- Cargo.lock
- Cargo.toml
- src/lib/stats/actor.rs
- src/lib/stats/mod.rs
- src/lib/stats/protocol.rs
- src/lib/stats/resources.rs
- src/lib/web/routes/v1/stats.rs
- src/webpage/src/app.rs
- src/webpage/src/stats/mod.rs
- src/webpage/src/stats/resources.rs
> provide resource information

- .github/workflows/build.yml
> ci: Add submodule recursive

- src/webpage/src/app.rs
- src/webpage/src/messages.rs
> App: show non numeric values

- src/lib/drivers/udp/client.rs
Tested only in macos, does not work with it
> dirvers: udp: client: Remove unnecessary connect

- .github/workflows/test_endpoints.yml
- tests/scripts/test_heartbeat.py
> tests: scripts: Add test_heartbeat

- Cargo.lock
- Cargo.toml
- src/lib/drivers/rest/autopilot/parameters/mod.rs
Decrease binary size from 250MB to 78MB
> Cargo: Use include_dir with glob pattern

- Cargo.lock
- Cargo.toml
- src/lib/logger.rs
- src/main.rs
Note: log filename prefix changed from `mavlink-router-rs` to `mavlink-server`.
> Move to upstream tracing-appender

- Cargo.lock
- Cargo.toml
- src/lib/drivers/udp/server.rs
Fix bug in loop where the socket can show as already binded 
Fix #169
> Update udp server to reuse the address

- tests/python/control.py
- tests/python/main.py
- tests/python/pyproject.toml
Add set mode
Add gps fix check
Add simple yaw commands test
> Add more control tests

- src/lib/drivers/generic_tasks.rs
- src/lib/drivers/udp/client.rs
- src/lib/drivers/udp/server.rs
> src: lib: drivers: Better treat IO errors
