bluerobotics/mavlink-server

- src/drivers/fake.rs
- src/drivers/file/server.rs
- src/drivers/mod.rs
- src/drivers/tcp/client.rs
- src/drivers/tcp/mod.rs
- src/drivers/tcp/server.rs
- src/drivers/udp/client.rs
- src/drivers/udp/server.rs
- src/hub.rs
- src/protocol.rs
The idea of this change is to prepare the drivers to have multiple callbacks, which will be used as filters. Why? Because instead of copying the 300 bytes of data for each filter and for each channel's subscriber, we use a smart pointer.
The main drawback is that this Arc can cause a memory leak if the implementation of both Drivers and their callbacks clones it to a forever-living entity, like a loop task or a task that gets locked somehow.
> Move to arc

- Cargo.lock
- Cargo.toml
- benches/callbacks_bench.rs
- src/drivers/fake.rs
- src/drivers/file/client.rs
- src/drivers/file/server.rs
- src/drivers/mod.rs
- src/drivers/serial/mod.rs
- src/drivers/tcp/client.rs
- src/drivers/tcp/mod.rs
- src/drivers/tcp/server.rs
- src/drivers/udp/client.rs
- src/drivers/udp/server.rs
- src/lib/callbacks.rs
- src/lib/mod.rs
_harder better faster stronger_
_stronger_ because this PR allows many callbacks to be set, instead of a single one. This will allow us to have multiple configurable filters in the future.
_faster_ because it uses `indexmap` instead of `hashmap` (see the [crate](https://crates.io/crates/indexmap) for more details).
_better_ because it adds the callbacks and builder to every driver that didn't implement it yet.
_harder_ because  it adds a benchmark!
> More callbacks

- src/cli.rs
- src/drivers/fake.rs
- src/drivers/file/client.rs
- src/drivers/file/server.rs
- src/drivers/mod.rs
- src/drivers/serial/mod.rs
- src/drivers/tcp/client.rs
- src/drivers/tcp/server.rs
- src/drivers/udp/client.rs
- src/drivers/udp/server.rs
> cli: Use drivers to create help

- src/hub/actor.rs
- src/hub/mod.rs
- src/hub/protocol.rs
- src/main.rs
This allows us to have multiple controllers, like a TUI and a REST working concurrently while also allowing multiple Hubs to be instantiated, if needed.
> src: Make Hub into a thread-safe facade that interacts with the hub actor

- src/drivers/fake.rs
- src/drivers/mod.rs
- src/drivers/serial/mod.rs
- src/drivers/tcp/client.rs
- src/drivers/tcp/mod.rs
- src/drivers/tcp/server.rs
- src/drivers/tlog/reader.rs
- src/drivers/tlog/writer.rs
- src/drivers/udp/client.rs
- src/drivers/udp/server.rs
- src/hub/actor.rs
- src/hub/mod.rs
- src/hub/protocol.rs
- src/stats/actor.rs
- src/stats/driver.rs
- src/stats/mod.rs
- src/stats/protocol.rs
Basically breaking the chore and renaming from the HubStats work so we can better review them.
> General improvements before adding Hub Stats

- src/hub/actor.rs
- src/hub/mod.rs
- src/hub/protocol.rs
- src/stats/actor.rs
- src/stats/driver.rs
- src/stats/mod.rs
- src/stats/protocol.rs
This PR uses the same metrics from drivers for the hub.
> Add hub stats

- Cargo.lock
- Cargo.toml
- src/cli.rs
- src/drivers/mod.rs
- src/drivers/rest/mod.rs
- src/web/mod.rs
Add websocket communication and cross-websocket communication via mavlink2rest API
> Add rest api (websocket for now)

- src/stats/accumulated/mod.rs
This information is important for future REST API.
> Add last message in accumulated

- .github/workflows/build.yml
This reverts commit 384ad2d780e4af693fdf4faca7292b02d685bde1.
It should be fine with the latest version
> Revert "ci: Fix binstall step for now"

- src/webpage/src/app.rs
> Move frontend to use dock

- src/lib/drivers/rest/data.rs
- src/lib/drivers/rest/mod.rs
- src/lib/drivers/zenoh/mod.rs
- src/lib/mavlink_json.rs
- src/lib/mod.rs
- src/webpage/src/app.rs
- src/webpage/src/messages.rs
> Improve mavlink json

- src/lib/cli.rs
- src/lib/hub/actor.rs
This brings [this feature](https://github.com/mavlink/mavlink2rest/pull/107/files) here, helps #44.
> Add send initial hearbeats cli arg

- Cargo.lock
- Cargo.toml
- src/lib/cli.rs
- src/lib/drivers/mod.rs
This will allow us to fix the test errors introduced by #101.
The problem happens when a test code calls any of the functions of the cli module, which then makes the `lazy_static` to create `cli::Args` from the commandline of the binary being executed, conflicting with the test harness/setup.
This change allows us to define the parsed `cli::Args` so that it won't conflict with the arguments being passed to the test harness/setup.
.. yeah, this is a drawback of singletons using `lazy_static`.
> Fix cli on tests

- src/lib/web/routes/v1/rest/mavlink.rs
- src/lib/web/routes/v1/rest/mod.rs
> web: v1: rest: mavlink: Add helper endpoint

- src/lib/drivers/fake.rs
- src/lib/drivers/mod.rs
- src/lib/hub/mod.rs
- src/lib/logger.rs
- src/lib/stats/accumulated/driver.rs
- src/lib/stats/accumulated/messages.rs
- src/lib/stats/mod.rs
- src/lib/stats/protocol.rs
- src/main.rs
Sort to use: std, external, crate, as pointed in: https://github.com/bluerobotics/mavlink-server/pull/104#discussion_r1881940663
> Fix use order 

- src/lib/drivers/mod.rs
Fix issue where url based entries are being processed as legacy
> src: drivers: mod: Ignore :// when running legacy mode

- .github/workflows/build.yml
- Cargo.lock
- Cargo.toml
- src/lib/drivers/generic_tasks.rs
- src/lib/drivers/mod.rs
- src/lib/drivers/rest/mod.rs
- src/lib/drivers/serial/mod.rs
- src/lib/drivers/tcp/client.rs
- src/lib/drivers/tcp/server.rs
- src/lib/drivers/udp/client.rs
- src/lib/drivers/udp/mod.rs
- src/lib/drivers/udp/server.rs
- src/lib/drivers/zenoh/mod.rs
- src/main.rs
- tests/udp.rs
Initial version that allows drivers to implement direction, allowing to receive or/and send
> Add driver direction

- .github/workflows/build.yml
- src/lib/drivers/generic_tasks.rs
- src/lib/drivers/tcp/client.rs
- src/lib/drivers/tcp/server.rs
- tests/tcp.rs
> TCP: Add direction control

- src/lib/cli.rs
With this patch we can pass env variables within the args, as in:
``` bash
export WEB_SERVER=127.0.0.1:1234
export FAKECLIENT_KIND=debug
cargo run -- \
--verbose \
--log-path $PWD/logs \
--web-server $WEB_SERVER \
fakeclient://$FAKECLIENT_KIND
```
> src: lib: cli: Expand all args, and canonize logpath

- Cargo.lock
- Cargo.toml
- src/lib/drivers/fake.rs
- src/lib/drivers/mod.rs
- src/lib/drivers/tlog/writer.rs
- src/lib/hub/mod.rs
- src/main.rs
Two main things here:
1. Fixes tlog aborting when lagged.
2. Now the fake source can finally be used for pressure testing!
Ex:
```bash
export PERIOD_US=10
cargo run --release -- \
"fakesrc://?period_us=$PERIOD_US&component_id=40" \
"fakesink://?print_as_json=false" \
"tlogwriter://$PWD/logs/test.tlog"
```
By changing the `PERIOD_US` value, we can see how the system behaves with too much pressure, recreating the lag-snowball effect, which slows down the drivers even more.
A solution for that snowball problem could be to drop all lagged messages. While dropping messages allows the system to recover faster, that would make the system less reliant on transitory overloads. To balance that, a bigger hub channel buffer could help.
This PR doesn't touch on the pressure problem, just allows us to …
> Improve drivers

- .gitignore
- Cargo.lock
- Cargo.toml
- src/lib/drivers/generic_tasks.rs
- src/lib/drivers/udp/client.rs
- src/lib/drivers/udp/server.rs
- src/lib/hub/actor.rs
Reverts #168 and re-fixes #169.
The problem with the previous fix is that while it allows the UDP Server to rebind and recreate its receiving task, the sender tasks would remain alive. This was the last piece to understand the puzzle. Here's the whole bug story:
1. When a sequence of wrong CRC and truncated message arrived at the UDP Server receiving task, it was failing with the Io Error `kind: Other, error: "bytes remaining on stream"`, breaking from the loop, returning from the `udp_receive_task` with a `Result::Ok` (instead of a `Result::Error`).
2. Then, the UDP Server runner loop would try to recover by binding again to the same port, which should be fine, but because the socket was shared with the clients' task using an Arc, they would still hold the resource, preventing new …
> Fix udp server clients

- .github/workflows/build.yml
> .github: Install cargo fmt before using it
